apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-existing-app
  namespace: argocd
  # Lưu ý: Không cấu hình finalizer `resources-finalizer.argocd.argoproj.io` 
  # để tránh việc vô tình xóa Application làm xóa theo resource trên K8s.
spec:
  project: default
  source:
    repoURL: 'https://github.com/themingw666/test.git'  # Thay bằng URL Git của bạn
    targetRevision: master                                   # Nhánh (VD: main / master / commit / tag)
    path: apps                                             # Đường dẫn thư mục chứa YAML trong Git repo

  destination:
    server: 'https://kubernetes.default.svc'               # Địa chỉ Kubernetes cluster
    namespace: default                                     # Namespace nơi resource đang chạy thực tế

  syncPolicy:
    syncOptions:
      - CreateNamespace=false       # Không cố tạo lại namespace nếu đã tồn tại
      - ApplyOutOfSyncOnly=true     # Chỉ cập nhật các resource / field có sự sai khác
      - ServerSideApply=true        # Dùng Server-Side Apply để merge cấu hình thay vì đè toàn bộ
      # - RespectIgnoreDifferences=true
    
    # automated:                    # Cân nhắc bật sau khi đã sync thủ công lần đầu thành công
    #   prune: false                # Tắt prune để không xóa bất kỳ resource nào ngoài git
    #   selfHeal: true
