apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-1-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: cdtmcqg
    app.kubernetes.io/environment: development
spec:
  project: default
  source:
    repoURL: https://git-cmcdtqg.mbfs.vn/dev-sec-ops/gitops.git
    targetRevision: master
    path: environments/dev/project-a/service-1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      [
        ServerSideApply=true,
        ApplyOutOfSyncOnly=true,
        RespectIgnoreDifferences=true,
      ]
